Config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('products/', include('products.urls', namespace='products')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('pages.urls', namespace='pages')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path

from .views import BlogListView

app_name = 'blogs'

urlpatterns = [
    path('', BlogListView.as_view(), name='list')
]

orders/urls.py
from django.urls import path

from orders.views import add_or_remove_cart, WishlistListView, add_or_remove_wishlist, CartListView, \
    CheckoutTemplateView

app_name = "orders"

urlpatterns = [
    path("add-or-remove-cart/<int:pk>/", add_or_remove_cart, name="add-or-remove-cart"),
    path("add-or-remove-wishlist/<int:pk>/", add_or_remove_wishlist, name="add-or-remove-wishlist"),
    path("cart/", CartListView.as_view(), name="cart"),
    path("wishlist/", WishlistListView.as_view(), name="wishlist"),
    path("checkout/", CheckoutTemplateView.as_view(), name="checkout"),
]

templates/shop/product-cart.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}
{% load order_tags %}
{% block title %}Cart{% endblock %}
{% block body %}class="product-cart checkout-cart blog"{% endblock %}
{% block content %}
    <div class="main-content" id="cart">
        <!-- main -->
        <div id="wrapper-site">
            <!-- breadcrumb -->
            <nav class="breadcrumb-bg">
                <div class="container no-index">
                    <div class="breadcrumb">
                        <ol>
                            <li>
                                <a href="#">
                                    <span>Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>Shopping Cart</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
            </nav>
            <div class="container">
                <div class="row">
                    <div id="content-wrapper" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 onecol">
                        <section id="main">
                            <div class="cart-grid row">
                                <div class="col-md-9 col-xs-12 check-info">
                                    <h1 class="title-page">Shopping Cart</h1>
                                    <div class="cart-container">
                                        <div class="cart-overview js-cart">
                                            <ul class="cart-items">
                                                {% for product in products %}
                                                <li class="cart-item">
                                                    <div class="product-line-grid row justify-content-between">
                                                        <!--  product left content: image-->
                                                        <div class="product-line-grid-left col-md-2">
                                                            <span class="product-image media-middle">
                                                                <a href="product-detail.html">
                                                                    <img class="img-fluid" src="{{ product.image1.url }}"
                                                                         alt="Organic Strawberry Fruits">
                                                                </a>
                                                            </span>
                                                        </div>
                                                        <div class="product-line-grid-body col-md-6">
                                                            <div class="product-line-info">
                                                                <a class="label" href="product-detail.html"
                                                                   data-id_customization="0">{{ product.title }}</a>
                                                            </div>
                                                            <div class="product-line-info product-price">
                                                                <span class="value">£20.00</span>
                                                            </div>
                                                            <div class="product-line-info">
                                                                <span class="label-atrr">Size:</span>
                                                                <span class="value">S</span>
                                                            </div>
                                                            <div class="product-line-info">
                                                                <span class="label-atrr">Color:</span>
                                                                <span class="value">Blue</span>
                                                            </div>
                                                        </div>
                                                        <div class="product-line-grid-right text-center product-line-actions col-md-4">
                                                            <div class="row">
                                                                <div class="col-md-5 col qty">
                                                                    <div class="label">Qty:</div>
                                                                    <div class="quantity">
                                                                        <input type="text" name="qty" value="1"
                                                                               class="input-group form-control">

                                                                        <span class="input-group-btn-vertical">
                                                                            <button class="btn btn-touchspin js-touchspin bootstrap-touchspin-up"
                                                                                    type="button">
                                                                                +
                                                                            </button>
                                                                            <button class="btn btn-touchspin js-touchspin bootstrap-touchspin-down"
                                                                                    type="button">
                                                                                -
                                                                            </button>
                                                                        </span>
                                                                    </div>
                                                                </div>
                                                                <div class="col-md-5 col price">
                                                                    <div class="label">Total:</div>
                                                                    <div class="product-price total">
                                                                        £20.00
                                                                    </div>
                                                                </div>
                                                                <div class="col-md-2 col text-xs-right align-self-end">
                                                                    <div class="cart-line-product-actions ">
                                                                        <a class="remove-from-cart" rel="nofollow"
                                                                           href="{% url 'orders:add-or-remove-cart' pk=product.id %}?next={{ request.path }}?{{ request.GET.urlencode }}" data-link-action="delete-from-cart"
                                                                           data-id-product="1">
                                                                            <i class="fa fa-trash-o"
                                                                               aria-hidden="true"></i>
                                                                        </a>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                                    <a href="product-checkout.html" class="continue btn btn-primary pull-xs-right">
                                        Continue
                                    </a>
                                </div>
                                <div class="cart-grid-right col-xs-12 col-lg-3">
                                    <div class="cart-summary">
                                        <div class="cart-detailed-totals">
                                            <div class="cart-summary-products">
                                                <div class="summary-label">There are 3 item in your cart</div>
                                            </div>
                                            <div class="cart-summary-line" id="cart-subtotal-products">
                                                <span class="label js-subtotal">
                                                    Total products:
                                                </span>
                                                <span class="value">£200.00</span>
                                            </div>
                                            <div class="cart-summary-line" id="cart-subtotal-shipping">
                                                <span class="label">
                                                    Total Shipping:
                                                </span>
                                                <span class="value">Free</span>
                                                <div>
                                                    <small class="value"></small>
                                                </div>
                                            </div>
                                            <div class="cart-summary-line cart-total">
                                                <span class="label">Total:</span>
                                                <span class="value">£200.00 (tax incl.)</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="block-reassurance">
                                        <ul>
                                            <li>
                                                <div class="block-reassurance-item">
                                                    <img src="{% static 'img/product/check1.png' %}"
                                                         alt="Security policy (edit with Customer reassurance module)">
                                                    <span>Security policy (edit with Customer reassurance module)</span>
                                                </div>
                                            </li>
                                            <li>
                                                <div class="block-reassurance-item">
                                                    <img src="{% static 'img/product/check2.png' %}"
                                                         alt="Delivery policy (edit with Customer reassurance module)">
                                                    <span>Delivery policy (edit with Customer reassurance module)</span>
                                                </div>
                                            </li>
                                            <li>
                                                <div class="block-reassurance-item">
                                                    <img src="{% static 'img/product/check3.png' %}"
                                                         alt="Return policy (edit with Customer reassurance module)">
                                                    <span>Return policy (edit with Customer reassurance module)</span>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/shop/product-checkout.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}Checkout{% endblock %}
{% block body %}class="product-checkout checkout-cart"{% endblock %}
{% block content %}
    <div id="checkout" class="main-content">
        <div class="wrap-banner">
            <!-- breadcrumb -->
            <nav class="breadcrumb-bg">
                <div class="container no-index">
                    <div class="breadcrumb">
                        <ol>
                            <li>
                                <a href="#">
                                    <span>Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>Checkout</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
            </nav>

            <!-- main -->
            <div id="wrapper-site">
                <div class="container">
                    <div class="row">
                        <div id="content-wrapper" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 onecol">
                            <div id="main">
                                <div class="cart-grid row">
                                    <div class="col-md-9 check-info">
                                        <div class="checkout-personal-step">
                                            <h3 class="step-title h3 info">
                                                <span class="step-number">1</span>PERSONAL INFORMATION
                                            </h3>
                                        </div>
                                        <div class="content">
                                            <div class="tab-content">
                                                <div class="tab-pane fade in active show" id="checkout-guest-form"
                                                     role="tabpanel">
                                                    <form action="{% url 'orders:checkout' %}" id="customer-form" class="js-customer-form"
                                                          method="post">
                                                        {% csrf_token %}
                                                        <div>
                                                            <input type="hidden" name="id_customer" value="">
                                                            <div class="form-group row">
                                                                <input class="form-control" name="full_name" type="text"
                                                                       placeholder="Full name">
                                                            </div>
                                                            <div class="form-group row">
                                                                <input class="form-control" name="email" type="email"
                                                                       placeholder="Email">
                                                            </div>
                                                            <div class="form-group row">
                                                                <input class="form-control" name="phone_number" type="text"
                                                                       placeholder="Phone">
                                                            </div>
                                                            <div class="form-group row">
                                                                <input class="form-control" name="address" type="text"
                                                                       placeholder="Address">
                                                            </div>
                                                            <div class="form-group row check-input">
                                                                <span class="custom-checkbox d-inline-flex">
                                                                    <input class="check" name="optin" type="checkbox"
                                                                           value="1">
                                                                    <label class="label-absolute">Receive offers from our partners</label>
                                                                </span>
                                                            </div>
                                                            <div class="form-group row">
                                                                <span class="custom-checkbox d-inline-flex check-input">
                                                                    <input class="check" name="newsletter"
                                                                           type="checkbox" value="1">
                                                                    <label>Sign up for our newsletter
                                                                        <br>
                                                                        <em>You may unsubscribe at any moment. For that purpose,
                                                                            please find our contact info in the legal notice.
                                                                        </em>
                                                                    </label>
                                                                </span>
                                                            </div>
                                                        </div>
                                                        <div class="clearfix">
                                                            <div class="row">
                                                                <input type="hidden" name="submitCreate" value="1">

                                                                <button class="continue btn btn-primary pull-xs-right"
                                                                        name="continue"
                                                                        data-link-action="register-new-customer"
                                                                        type="submit"
                                                                        value="1">
                                                                    Continue
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="cart-grid-right col-xs-12 col-lg-3">
                                        <div class="cart-summary">
                                            <div class="cart-detailed-totals">
                                                <div class="cart-summary-products">
                                                    <div class="summary-label">There are 3 item in your cart</div>
                                                </div>
                                                <div class="cart-summary-line" id="cart-subtotal-products">
                                                    <span class="label js-subtotal">
                                                        Total products:
                                                    </span>
                                                    <span class="value">£200.00</span>
                                                </div>
                                                <div class="cart-summary-line" id="cart-subtotal-shipping">
                                                    <span class="label">
                                                        Total Shipping:
                                                    </span>
                                                    <span class="value">Free</span>
                                                    <div>
                                                        <small class="value"></small>
                                                    </div>
                                                </div>
                                                <div class="cart-summary-line cart-total">
                                                    <span class="label">Total:</span>
                                                    <span class="value">£200.00 (tax incl.)</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="block-reassurance">
                                            <ul>
                                                <li>
                                                    <div class="block-reassurance-item">
                                                        <img src="{% static 'img/product/check1.png' %}"
                                                             alt="Security policy (edit with Customer reassurance module)">
                                                        <span>Security policy (edit with Customer reassurance module)</span>
                                                    </div>
                                                </li>
                                                <li>
                                                    <div class="block-reassurance-item">
                                                        <img src="{% static 'img/product/check2.png' %}"
                                                             alt="Delivery policy (edit with Customer reassurance module)">
                                                        <span>Delivery policy (edit with Customer reassurance module)</span>
                                                    </div>
                                                </li>
                                                <li>
                                                    <div class="block-reassurance-item">
                                                        <img src="{% static 'img/product/check3.png' %}"
                                                             alt="Return policy (edit with Customer reassurance module)">
                                                        <span>Return policy (edit with Customer reassurance module)</span>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}